import Header from "@/components/header/header.component";
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/components/footer/footer.component";
import AuthProvider from "@/components/auth-provider/auth-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next-Auth-TailwindCss",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Header />
          {children}
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
